using System.Collections.Generic;
using UnityEngine;

public class CreatureData
{
	private static Dictionary<TechType, BehaviourType> behaviourTypeList = new Dictionary<TechType, BehaviourType>(TechTypeExtensions.sTechTypeComparer)
	{
		{
			TechType.BrainCoral,
			BehaviourType.Coral
		},
		{
			TechType.BigCoralTubes,
			BehaviourType.Coral
		},
		{
			TechType.HoleFish,
			BehaviourType.SmallFish
		},
		{
			TechType.GarryFish,
			BehaviourType.SmallFish
		},
		{
			TechType.Eyeye,
			BehaviourType.SmallFish
		},
		{
			TechType.LavaEyeye,
			BehaviourType.SmallFish
		},
		{
			TechType.Bladderfish,
			BehaviourType.SmallFish
		},
		{
			TechType.Hoverfish,
			BehaviourType.SmallFish
		},
		{
			TechType.Reginald,
			BehaviourType.SmallFish
		},
		{
			TechType.Bleeder,
			BehaviourType.SmallFish
		},
		{
			TechType.Rockgrub,
			BehaviourType.SmallFish
		},
		{
			TechType.Hoopfish,
			BehaviourType.SmallFish
		},
		{
			TechType.Spinefish,
			BehaviourType.SmallFish
		},
		{
			TechType.Boomerang,
			BehaviourType.MediumFish
		},
		{
			TechType.LavaBoomerang,
			BehaviourType.MediumFish
		},
		{
			TechType.Peeper,
			BehaviourType.MediumFish
		},
		{
			TechType.Oculus,
			BehaviourType.MediumFish
		},
		{
			TechType.RabbitRay,
			BehaviourType.MediumFish
		},
		{
			TechType.Cutefish,
			BehaviourType.MediumFish
		},
		{
			TechType.LavaLarva,
			BehaviourType.MediumFish
		},
		{
			TechType.Jellyray,
			BehaviourType.MediumFish
		},
		{
			TechType.Spadefish,
			BehaviourType.MediumFish
		},
		{
			TechType.Mesmer,
			BehaviourType.MediumFish
		},
		{
			TechType.Biter,
			BehaviourType.MediumFish
		},
		{
			TechType.Blighter,
			BehaviourType.MediumFish
		},
		{
			TechType.GhostRayBlue,
			BehaviourType.MediumFish
		},
		{
			TechType.GhostRayRed,
			BehaviourType.MediumFish
		},
		{
			TechType.HoopfishSchool,
			BehaviourType.MediumFish
		},
		{
			TechType.Player,
			BehaviourType.Shark
		},
		{
			TechType.CrashHome,
			BehaviourType.Trap
		},
		{
			TechType.Crash,
			BehaviourType.Trap
		},
		{
			TechType.Crabsnake,
			BehaviourType.Trap
		},
		{
			TechType.GasPod,
			BehaviourType.Poison
		},
		{
			TechType.HangingStinger,
			BehaviourType.Poison
		},
		{
			TechType.Jumper,
			BehaviourType.Crab
		},
		{
			TechType.CaveCrawler,
			BehaviourType.Crab
		},
		{
			TechType.Shuttlebug,
			BehaviourType.Crab
		},
		{
			TechType.RockPuncher,
			BehaviourType.Crab
		},
		{
			TechType.SeaTreader,
			BehaviourType.Crab
		},
		{
			TechType.CrabSquid,
			BehaviourType.Crab
		},
		{
			TechType.PrecursorDroid,
			BehaviourType.Crab
		},
		{
			TechType.Stalker,
			BehaviourType.Shark
		},
		{
			TechType.Sandshark,
			BehaviourType.Shark
		},
		{
			TechType.BoneShark,
			BehaviourType.Shark
		},
		{
			TechType.SpineEel,
			BehaviourType.Shark
		},
		{
			TechType.Shocker,
			BehaviourType.Shark
		},
		{
			TechType.LavaLizard,
			BehaviourType.Shark
		},
		{
			TechType.Warper,
			BehaviourType.Shark
		},
		{
			TechType.Reefback,
			BehaviourType.Whale
		},
		{
			TechType.Gasopod,
			BehaviourType.Whale
		},
		{
			TechType.Seamoth,
			BehaviourType.Shark
		},
		{
			TechType.Exosuit,
			BehaviourType.Shark
		},
		{
			TechType.Cyclops,
			BehaviourType.Whale
		},
		{
			TechType.RocketBase,
			BehaviourType.Whale
		},
		{
			TechType.ReaperLeviathan,
			BehaviourType.Leviathan
		},
		{
			TechType.GhostLeviathan,
			BehaviourType.Leviathan
		},
		{
			TechType.GhostLeviathanJuvenile,
			BehaviourType.Leviathan
		},
		{
			TechType.SeaEmperor,
			BehaviourType.Leviathan
		},
		{
			TechType.SeaEmperorJuvenile,
			BehaviourType.Leviathan
		},
		{
			TechType.SeaDragon,
			BehaviourType.Leviathan
		}
	};

	private static readonly Dictionary<BehaviourType, EcoTargetType> ecoTargetByBehaviorTypeList = new Dictionary<BehaviourType, EcoTargetType>
	{
		{
			BehaviourType.Trap,
			EcoTargetType.Trap
		},
		{
			BehaviourType.SmallFish,
			EcoTargetType.SmallFish
		},
		{
			BehaviourType.MediumFish,
			EcoTargetType.MediumFish
		},
		{
			BehaviourType.Shark,
			EcoTargetType.Shark
		},
		{
			BehaviourType.Whale,
			EcoTargetType.Whale
		},
		{
			BehaviourType.Leviathan,
			EcoTargetType.Leviathan
		}
	};

	private static readonly Dictionary<TechType, TechType> creatureTypeList = new Dictionary<TechType, TechType>(TechTypeExtensions.sTechTypeComparer)
	{
		{
			TechType.GhostLeviathanJuvenile,
			TechType.GhostLeviathan
		},
		{
			TechType.ReefbackBaby,
			TechType.Reefback
		},
		{
			TechType.SeaEmperorBaby,
			TechType.SeaEmperor
		},
		{
			TechType.SeaEmperorJuvenile,
			TechType.SeaEmperor
		}
	};

	public static BehaviourType GetBehaviourType(GameObject obj)
	{
		TechType techType = CraftData.GetTechType(obj);
		return behaviourTypeList.GetOrDefault(techType, BehaviourType.Unknown);
	}

	public static BehaviourType GetBehaviourType(TechType techType)
	{
		return behaviourTypeList.GetOrDefault(techType, BehaviourType.Unknown);
	}

	public static EcoTargetType GetEcoTargetType(BehaviourType behaviourType)
	{
		return ecoTargetByBehaviorTypeList.GetOrDefault(behaviourType, EcoTargetType.None);
	}

	public static EcoTargetType GetEcoTargetType(GameObject obj)
	{
		return GetEcoTargetType(GetBehaviourType(obj));
	}

	public static EcoTargetType GetEcoTargetType(TechType techType)
	{
		return GetEcoTargetType(GetBehaviourType(techType));
	}

	public static TechType GetCreatureType(GameObject obj)
	{
		return GetCreatureType(CraftData.GetTechType(obj));
	}

	public static TechType GetCreatureType(TechType techType)
	{
		return creatureTypeList.GetOrDefault(techType, techType);
	}
}
